#cloud-config
repo_update: true
repo_upgrade: true
package_reboot_if_required: true

packages:
  - mlocate
  - docker.io
  - docker-compose

write_files:
  - content: |
      version: "3.7"

      services:
        traefik:
          image: "traefik:latest"
          container_name: "traefik"
          networks:
            - traefik-global-proxy
          ports:
            - "80:80"
          volumes:
            - "./traefik.yml:/etc/traefik/traefik.yml"
            - "./dynamic.yml:/etc/traefik/dynamic.yml"
            - "/run/docker.sock:/run/docker.sock:ro"

      networks:
        traefik-global-proxy:
          name: "traefik-global-proxy"

    path: /root/second/docker-compose.yml
    permissions: '0766'

  - content: |
      entrypoints:
        web:
          address: :80

      providers:
        file:
          filename: /etc/traefik/dynamic.yml
        docker:
          exposedByDefault = false
          network = "traefik-global-proxy"

    path: /root/second/traefik.yml
    permissions: '0644'

  - content: |
      http:
        routers:
          catchall:
            entryPoints:
              - "web"
            service: s3bucket
            rule: "PathPrefix(`/`)"
            priority: 1
        services:
          s3bucket:
            loadBalancer:
              passHostHeader: false
              servers:
                - url: https://${s3bucket}

    path: /root/second/dynamic.yml
    permissions: '0644'

runcmd:
  - usermod -aG docker ubuntu
  - cd /root/second
  - docker-compose -f docker-compose.yml up -d
