name: terraform github action
on: push
jobs:
  terratest:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - name: setup deps
        working-directory: test/
        run: go mod init "github.com/ysolis/flugel_s3" && go get -v -t -d && go mod tidy

      - name: terratest plan-apply-check-destroy
        working-directory: test/
        run: go test -v
