name: terraform github action
on: push
jobs:
  initial-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo $AWS_ACCESS_KEY_ID - $AWS_SECRET_ACCESS_KEY - $AWS_DEFAULT_REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
